[package]
name = "tz_db_transformer"
version = "0.1.0"
authors = ["Shylock Hg <33566796+Shylock-Hg@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
csv = "1.1"
